import { renderProductVisual } from './product-visual.js';
import { carregarCatalogo } from './data-service.js';
import { setupNavigation } from './navigation.js';
import { supabase } from './croma-supabase.js';

if(!document.querySelector('script[data-croma-cart]')){const script=document.createElement('script');script.src='/js/cart.js?v=20260821-2';script.dataset.cromaCart='1';document.head.appendChild(script)}
if(!document.querySelector('script[data-public-header-loader]')){const headerScript=document.createElement('script');headerScript.src='/js/service-header.js?v=20260831-5';headerScript.defer=true;headerScript.dataset.publicHeaderLoader='1';document.head.appendChild(headerScript)}
setupNavigation();

document.querySelectorAll('.hero-slide').forEach(slide=>{if(slide.textContent.includes('Croma Papelaria & Presentes')){const a=slide.querySelector('.hero-slide-actions a');if(a){a.href='/produtos/';a.textContent='Explorar produtos'}}});

const state={data:null,categoria:'Todos',termo:''};
const CATEGORY_ORDER=['Todos','Comunicação Visual','Gráfica','Eventos','Papelaria','Presentes','Eletrônicos','Digital'];
const WHATSAPP_NUMBER='553230253588',WHATSAPP_MESSAGE='Olá! Vim pelo Croma Hub e gostaria de solicitar um orçamento.';
const grid=document.querySelector('#catalogGrid'),filters=document.querySelector('#catalogFilters'),search=document.querySelector('#catalogSearch'),modal=document.querySelector('#productModal'),modalClose=document.querySelector('#modalClose'),whatsappCta=document.querySelector('#whatsappCta'),whatsappFloat=document.querySelector('#whatsappFloat'),whatsappClose=document.querySelector('#whatsappClose');
const normalizar=(text='')=>text.toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,''),moeda=value=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function itensFiltrados(){if(!state.data)return[];const termo=normalizar(state.termo.trim());return state.data.itens.filter(item=>(state.categoria==='Todos'||item.categoria===state.categoria)&&(!termo||normalizar(`${item.nome} ${item.categoria} ${item.descricao}`).includes(termo)))}
function categoriasDisponiveis(){const available=new Set([...(state.data?.categororias||[]),...(state.data?.categorias||[]),...(state.data?.itens||[]).map(item=>item.categoria).filter(Boolean)]);return CATEGORY_ORDER.filter(category=>available.has(category)).concat([...available].filter(category=>!CATEGORY_ORDER.includes(category)))}
function renderFilters(){if(!filters||!state.data)return;filters.innerHTML=categoriasDisponiveis().map(category=>`<button class="filter-btn ${category===state.categoria?'active':''}" data-category="${category}">${category}</button>`).join('')}
function renderCatalog(){if(!grid)return;const itens=itensFiltrados();if(!itens.length){grid.innerHTML='<div class="empty-state">Nenhum item encontrado. Tente outra busca ou categoria.</div>';return}grid.innerHTML=itens.map(item=>`<article class="product-card" aria-label="${item.nome}">${renderProductVisual(item)}<div class="product-body"><span class="product-category">${item.categoria}</span><h3>${item.nome}</h3><p>${item.descricao}</p>${item.precoVenda?`<div class="catalog-price"><small>${item.quantidadePreco||1} unidades a partir de</small><strong>${moeda(item.precoVenda)}</strong></div>`:''}<span class="product-more">Vitrine Croma</span></div></article>`).join('')}
filters?.addEventListener('click',event=>{const button=event.target.closest('[data-category]');if(!button)return;state.categoria=button.dataset.category;renderFilters();renderCatalog()});search?.addEventListener('input',event=>{state.termo=event.target.value;renderCatalog()});modalClose?.addEventListener('click',()=>modal?.close());whatsappCta?.addEventListener('click',event=>{event.preventDefault();window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(WHATSAPP_MESSAGE)}`,'_blank','noopener,noreferrer')});if(whatsappFloat&&whatsappClose){const hiddenUntil=Number(localStorage.getItem('cromaWhatsappHiddenUntil')||0);if(hiddenUntil>Date.now())whatsappFloat.hidden=true;whatsappClose.addEventListener('click',()=>{whatsappFloat.hidden=true;localStorage.setItem('cromaWhatsappHiddenUntil',String(Date.now()+86400000))})}

document.querySelectorAll('.service-card').forEach((card,i)=>{card.style.cursor='pointer';card.setAttribute('tabindex','0');const href=i===0?'/servicos/#comunicacao-visual':i===1?'/servicos/#servicos-graficos':i===2?'/produtos/':'/servicos/#eventos-personalizados';const go=()=>location.href=href;card.addEventListener('click',go);card.addEventListener('keydown',event=>{if(event.key==='Enter')go()})});

function injectVisualStyles(){if(document.querySelector('style[data-real-media-home]'))return;const s=document.createElement('style');s.dataset.realMediaHome='1';s.textContent=`.home-photo-card{position:relative;overflow:hidden;min-height:310px!important;background:#211c5c!important;color:#fff!important}.home-photo-card::before{content:'';position:absolute;inset:0;background-image:var(--photo);background-size:cover;background-position:center}.home-photo-card::after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(20,16,60,.08),rgba(20,16,60,.86))}.home-photo-card>*{position:relative;z-index:1}.home-photo-card h3,.home-photo-card p,.home-photo-card span{color:#fff!important}.portfolio-real-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.portfolio-real-card{position:relative;min-height:330px;border-radius:24px;overflow:hidden;background:#eceaf3}.portfolio-real-card img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.portfolio-real-card::after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 35%,rgba(20,16,60,.88))}.portfolio-real-copy{position:absolute;z-index:2;left:18px;right:18px;bottom:18px;color:#fff}.portfolio-real-copy strong{display:block;font-size:1.05rem}.portfolio-real-copy small{display:block;margin-top:4px;color:#e9e7f5}@media(max-width:900px){.portfolio-real-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.portfolio-real-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}

async function renderServiceHomePhotos(){const cards=[...document.querySelectorAll('#servicos .service-card')];if(!cards.length)return;const {data}=await supabase.from('catalog_categories').select('slug,image_url').in('slug',['comunicacao-visual','servicos-graficos','papelaria','eventos-personalizados']);const by=new Map((data||[]).map(x=>[x.slug,x.image_url]));const slugs=['comunicacao-visual','servicos-graficos','papelaria','eventos-personalizados'];cards.forEach((card,i)=>{const url=by.get(slugs[i]);if(url){card.classList.add('home-photo-card');card.style.setProperty('--photo',`url("${url}")`)}})}

async function renderPortfolioHome(){const section=document.querySelector('#portfolio');if(!section)return;const {data,error}=await supabase.from('portfolio_items').select('*').eq('active',true).order('sort_order').limit(4);if(error||!data?.length)return;const old=section.querySelector('.portfolio-grid');if(old)old.outerHTML=`<div class="portfolio-real-grid">${data.map(x=>`<article class="portfolio-real-card"><img src="${esc(x.image_url)}" alt="${esc(x.image_alt||x.title)}" loading="lazy"><div class="portfolio-real-copy"><strong>${esc(x.title)}</strong><small>${esc(x.description||'')}</small></div></article>`).join('')}</div>`;const note=section.querySelector('.section-note');if(note)note.textContent='Uma seleção visual das principais soluções e trabalhos apresentados pela Croma.'}

const about=document.querySelector('#sobre');if(about){const more=document.createElement('p');more.innerHTML='<a class="btn btn-ghost" href="/sobre/">Conhecer a Croma</a>';about.querySelector('.about-copy')?.appendChild(more)}

async function init(){injectVisualStyles();state.data=await carregarCatalogo();renderFilters();renderCatalog();await Promise.allSettled([renderServiceHomePhotos(),renderPortfolioHome()])}
init();