import{protectInternalPage}from'./interno-auth.js';import{migrateLocalState,saveModuleState}from'./interno-store.js';
const session=await protectInternalPage();if(!session)throw new Error('auth');
const K={p:['rd_processes','croma_rd_process_v1'],r:['rd_problems','croma_rd_problem_v1'],s:['rd_suppliers','croma_rd_supplier_v1']};
let[processes,problems,suppliers]=await Promise.all([migrateLocalState(...K.p,[]),migrateLocalState(...K.r,[]),migrateLocalState(...K.s,[])]);
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const saveP=()=>saveModuleState(K.p[0],processes),saveR=()=>saveModuleState(K.r[0],problems),saveS=()=>saveModuleState(K.s[0],suppliers);
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
async function seed(){if(processes.length)return;processes.push({name:'Revista / catálogo com lombada quadrada — processo artesanal',area:'Acabamento',status:'Em teste',date:new Date().toISOString().slice(0,10),purpose:'Usar quando o miolo é espesso demais para grampo canoa ou quando se deseja acabamento de lombada reta.',materials:'Miolo impresso e refilado; capa flexível; cola PVA adequada; prensa ou duas superfícies planas; espátula; serra fina para ranhuras leves quando necessário.',steps:'1. Blocar e alinhar o miolo.\n2. Fazer ranhuras leves e superficiais no lombo, se necessário.\n3. Aplicar camada fina e uniforme de cola no lombo.\n4. Aguardar pega inicial conforme a cola utilizada.\n5. Posicionar e alinhar a capa já vincada.\n6. Prensar sem deformar.\n7. Respeitar cura completa antes de abrir e refilar.',risks:'Evitar excesso de cola, ranhuras profundas, desalinhamento da capa, prensagem torta e abertura antes da cura. Papel fotográfico pode exigir atenção maior à aderência.',quality:'Verificar esquadro, centralização, abertura progressiva, folhas soltas, trincas no lombo e aderência da capa antes de entregar.',time:'Primeiros lotes devem ser tratados como teste de processo e aprovados antes de ofertar em escala.'});await saveP()}
function badge(s){return s==='Validado'?'ok':s==='Em teste'?'test':s==='Descontinuado'?'stop':''}
function renderProcesses(filter=''){const q=filter.toLowerCase().trim(),arr=processes.filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q));$('processList').innerHTML=arr.length?arr.map(x=>{const i=processes.indexOf(x);return`<article class="process"><div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div><h3>${esc(x.name)}</h3><p>${esc(x.area)} · ${x.date?x.date.split('-').reverse().join('/'):'Sem data'}</p></div><span class="pill ${badge(x.status)}">${esc(x.status)}</span></div><dl><dt>Quando usar</dt><dd>${esc(x.purpose)}</dd><dt>Materiais</dt><dd>${esc(x.materials)}</dd><dt>Passo a passo</dt><dd>${esc(x.steps)}</dd><dt>Pontos críticos</dt><dd>${esc(x.risks)}</dd><dt>Controle de qualidade</dt><dd>${esc(x.quality)}</dd><dt>Tempo / observações</dt><dd>${esc(x.time)}</dd></dl><div class="actions"><button class="btn alt" data-edit-process="${i}">Editar</button><button class="btn alt" data-print>Imprimir</button><button class="btn danger" data-del-process="${i}">Excluir</button></div></article>`}).join(''):'<p class="internal-muted">Nenhum processo encontrado.</p>'}
function renderProblems(){$('problemList').innerHTML=problems.length?problems.map((x,i)=>`<div class="row"><div><strong>${esc(x.process)}</strong><br><small>${esc(x.issue)}${x.solution?' · Solução: '+esc(x.solution):''}</small></div><div><span class="pill">${esc(x.level)}</span></div><div><span class="pill ${x.status==='Resolvido'?'ok':'test'}">${esc(x.status)}</span></div><button class="btn danger" data-del-problem="${i}">Excluir</button></div>`).join(''):'<p class="internal-muted">Nenhuma ocorrência registrada.</p>'}
function renderSuppliers(){$('supplierList').innerHTML=suppliers.length?suppliers.map((x,i)=>`<div class="row"><div><strong>${esc(x.material)}</strong><br><small>${esc(x.use)}${x.notes?' · '+esc(x.notes):''}</small></div><div>${esc(x.supplier)}</div><div><span class="pill">${esc(x.ref||'Sem referência')}</span></div><button class="btn danger" data-del-supplier="${i}">Excluir</button></div>`).join(''):'<p class="internal-muted">Nenhum material cadastrado.</p>'}
function updateKpis(){$('kProcesses').textContent=processes.length;$('kTesting').textContent=processes.filter(x=>x.status==='Em teste').length;$('kApproved').textContent=processes.filter(x=>x.status==='Validado').length;$('kProblems').textContent=problems.length}function render(){renderProcesses($('search').value);renderProblems();renderSuppliers();updateKpis()}
$('pDate').value=$('prDate').value=new Date().toISOString().slice(0,10);
function clearProcess(){['pName','pPurpose','pMaterials','pSteps','pRisks','pQuality','pTime'].forEach(id=>$(id).value='');$('pStatus').value='Em teste';$('pDate').value=new Date().toISOString().slice(0,10);$('saveProcess').dataset.edit='';$('saveProcess').textContent='Salvar processo'}
$('saveProcess').onclick=async()=>{if(!$('pName').value.trim())return alert('Informe o nome do processo.');const obj={name:$('pName').value.trim(),area:$('pArea').value,status:$('pStatus').value,date:$('pDate').value,purpose:$('pPurpose').value.trim(),materials:$('pMaterials').value.trim(),steps:$('pSteps').value.trim(),risks:$('pRisks').value.trim(),quality:$('pQuality').value.trim(),time:$('pTime').value.trim()};const edit=$('saveProcess').dataset.edit;if(edit!=='')processes[Number(edit)]=obj;else processes.unshift(obj);await saveP();clearProcess();render();document.querySelector('[data-tab="library"]').click()};$('clearProcess').onclick=clearProcess;
document.body.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.print!=null)window.print();if(b.dataset.editProcess!=null){const i=+b.dataset.editProcess,x=processes[i];$('pName').value=x.name;$('pArea').value=x.area;$('pStatus').value=x.status;$('pDate').value=x.date;$('pPurpose').value=x.purpose;$('pMaterials').value=x.materials;$('pSteps').value=x.steps;$('pRisks').value=x.risks;$('pQuality').value=x.quality;$('pTime').value=x.time;$('saveProcess').dataset.edit=i;$('saveProcess').textContent='Atualizar processo';document.querySelector('[data-tab="newprocess"]').click();scrollTo({top:0,behavior:'smooth'})}if(b.dataset.delProcess!=null&&confirm('Excluir este processo?')){processes.splice(+b.dataset.delProcess,1);await saveP();render()}if(b.dataset.delProblem!=null){problems.splice(+b.dataset.delProblem,1);await saveR();render()}if(b.dataset.delSupplier!=null){suppliers.splice(+b.dataset.delSupplier,1);await saveS();render()}});
$('saveProblem').onclick=async()=>{if(!$('prProcess').value.trim()||!$('prIssue').value.trim())return alert('Informe o processo e o problema.');problems.unshift({process:$('prProcess').value.trim(),date:$('prDate').value,level:$('prLevel').value,status:$('prStatus').value,issue:$('prIssue').value.trim(),cause:$('prCause').value.trim(),solution:$('prSolution').value.trim(),prevention:$('prPrevention').value.trim()});['prProcess','prIssue','prCause','prSolution','prPrevention'].forEach(id=>$(id).value='');await saveR();render()};
$('saveSupplier').onclick=async()=>{if(!$('sMaterial').value.trim())return alert('Informe o material.');suppliers.unshift({material:$('sMaterial').value.trim(),supplier:$('sSupplier').value.trim(),ref:$('sRef').value.trim(),use:$('sUse').value.trim(),notes:$('sNotes').value.trim()});['sMaterial','sSupplier','sRef','sUse','sNotes'].forEach(id=>$(id).value='');await saveS();render()};$('search').oninput=e=>renderProcesses(e.target.value);await seed();render();
