import { supabase } from './croma-supabase.js';

const root=document.querySelector('#productCatalogRoot');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const PAGE_SIZE=48;
let families=[],categories=[],products=[],page=1,selectedCategory='',searchTerm='';
const mediaCache=new Map();

function familyCategories(id){return categories.filter(c=>c.family_id===id&&c.ativo!==false).sort((a,b)=>(a.ordem||0)-(b.ordem||0)||String(a.nome).localeCompare(String(b.nome),'pt-BR'))}
function descendants(id){const out=new Set([id]);let changed=true;while(changed){changed=false;for(const c of categories)if(c.parent_id&&out.has(c.parent_id)&&!out.has(c.id)){out.add(c.id);changed=true}}return out}
function familyMedia(f){return f?.image_url||''}
function categoryMedia(c,f){return c?.image_url||familyMedia(f)||''}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function setUrl(family='',category=''){const u=new URL(location.href);u.searchParams.delete('familia');u.searchParams.delete('categoria');if(family)u.searchParams.set('familia',family);if(category)u.searchParams.set('categoria',category);history.replaceState({},'',u.pathname+(u.search?u.search:''))}

function familyCard(f){const media=familyMedia(f);return `<article class="public-family-card" data-family-card="${esc(f.slug)}"><button type="button" class="public-family-trigger" data-family-trigger="${esc(f.slug)}" aria-expanded="false"><div class="public-family-media">${media?`<img src="${esc(media)}" alt="${esc(f.image_alt||f.nome)}" loading="lazy">`:''}</div><div class="public-family-copy"><h2>${esc(f.nome)}</h2><p>${esc(f.descricao||'Conheça as categorias desta família.')}</p><span class="public-family-action">Ver categorias ↓</span></div></button><div class="public-family-detail" data-family-detail></div></article>`}

function renderShell(){root.innerHTML=`<div class="public-breadcrumb"><a href="/">Início</a><span>›</span><strong>Produtos</strong></div><div class="public-intro"><span class="public-eyebrow">Croma Papelaria & Presentes</span><h1>Produtos</h1><p class="public-lead">Explore o catálogo por famílias. As categorias serão organizadas na próxima etapa sem alterar os produtos originais do Bling.</p></div><section><div class="public-family-grid" id="productFamilyGrid">${families.map(familyCard).join('')}</div></section><section class="public-section"><div class="public-section-head"><div><span class="public-eyebrow">Catálogo completo</span><h2 class="public-section-title">Encontre um produto</h2><p>Enquanto classificamos as categorias, todos os produtos ativos continuam disponíveis pela busca.</p></div><input class="public-search" id="productSearch" type="search" placeholder="Buscar por nome ou SKU"></div><div id="productResults"><div class="public-empty">Carregando produtos...</div></div></section>`;
 root.querySelectorAll('[data-family-trigger]').forEach(b=>b.addEventListener('click',()=>toggleFamily(b.dataset.familyTrigger)));
 const search=root.querySelector('#productSearch');search.value=searchTerm;search.addEventListener('input',()=>{searchTerm=search.value.trim().toLowerCase();page=1;renderProducts()});
 const params=new URLSearchParams(location.search),familySlug=params.get('familia')||'',catSlug=params.get('categoria')||'';
 if(catSlug){const cat=categories.find(c=>c.slug===catSlug);if(cat){selectedCategory=cat.id;searchTerm='';search.value='';page=1;renderProducts();const fam=families.find(f=>f.id===cat.family_id);if(fam)requestAnimationFrame(()=>openFamily(fam.slug,false))}}
 else if(familySlug)requestAnimationFrame(()=>openFamily(familySlug,false));
 renderProducts();
}

function closeFamilies(update=true){root.querySelectorAll('[data-family-card]').forEach(card=>{card.classList.remove('is-expanded');card.querySelector('[data-family-trigger]')?.setAttribute('aria-expanded','false');const detail=card.querySelector('[data-family-detail]');if(detail)detail.innerHTML=''});if(update){selectedCategory='';setUrl('','')}}
function toggleFamily(slug){const card=root.querySelector(`[data-family-card="${CSS.escape(slug)}"]`);if(card?.classList.contains('is-expanded'))closeFamilies();else openFamily(slug,true)}
function openFamily(slug,scroll=true){const f=families.find(x=>x.slug===slug),card=root.querySelector(`[data-family-card="${CSS.escape(slug)}"]`);if(!f||!card)return;closeFamilies(false);card.classList.add('is-expanded');card.querySelector('[data-family-trigger]')?.setAttribute('aria-expanded','true');const cats=familyCategories(f.id),detail=card.querySelector('[data-family-detail]');detail.innerHTML=`<div class="public-family-detail-head"><div><h3>Escolha uma categoria</h3><p>${cats.length?'Selecione uma categoria para ver os produtos relacionados.':'As categorias desta família serão definidas na próxima etapa.'}</p></div><button class="public-close" type="button" data-family-close>Fechar</button></div>${cats.length?`<div class="public-card-grid">${cats.map(c=>{const media=categoryMedia(c,f);return `<button type="button" class="public-card" data-category-id="${c.id}" data-category-slug="${esc(c.slug)}" style="padding:0;text-align:left;cursor:pointer"><div class="public-card-media">${media?`<img src="${esc(media)}" alt="${esc(c.image_alt||c.nome)}" loading="lazy">`:''}</div><div class="public-card-copy"><h3>${esc(c.nome)}</h3><p>${esc(c.descricao||'Ver produtos desta categoria.')}</p></div></button>`}).join('')}</div>`:'<div class="public-empty">Família criada e pronta para receber categorias.</div>'}`;detail.querySelector('[data-family-close]')?.addEventListener('click',e=>{e.stopPropagation();closeFamilies()});detail.querySelectorAll('[data-category-id]').forEach(b=>b.addEventListener('click',()=>{selectedCategory=b.dataset.categoryId;page=1;setUrl(f.slug,b.dataset.categorySlug);renderProducts();root.querySelector('#productResults')?.scrollIntoView({behavior:'smooth',block:'start'})}));setUrl(f.slug,'');if(scroll)requestAnimationFrame(()=>card.scrollIntoView({behavior:'smooth',block:'nearest'}))}

async function ensureMedia(ids){const missing=ids.filter(id=>!mediaCache.has(id));if(!missing.length)return;for(let i=0;i<missing.length;i+=150){const chunk=missing.slice(i,i+150);const{data,error}=await supabase.from('product_media').select('product_id,url,alt_text,is_primary,ordem,ativo,kind').in('product_id',chunk).eq('ativo',true).eq('kind','image').order('is_primary',{ascending:false}).order('ordem');if(error)throw error;for(const id of chunk)mediaCache.set(id,null);for(const m of data||[])if(m.product_id&&m.url&&!mediaCache.get(m.product_id))mediaCache.set(m.product_id,m)}}

async function renderProducts(){const box=root.querySelector('#productResults');if(!box)return;let rows=products;if(selectedCategory){const allowed=descendants(selectedCategory);rows=rows.filter(p=>allowed.has(p.catalog_category_id))}if(searchTerm)rows=rows.filter(p=>[p.nome,p.sku].some(v=>String(v||'').toLowerCase().includes(searchTerm)));const total=rows.length,pages=Math.max(1,Math.ceil(total/PAGE_SIZE));if(page>pages)page=pages;const shown=rows.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);box.innerHTML='<div class="public-empty">Carregando produtos...</div>';try{await ensureMedia(shown.map(p=>p.id));box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;margin:0 0 14px"><strong style="color:var(--pc-deep)">${total} produto(s)</strong>${selectedCategory?'<button type="button" class="public-close" id="clearProductCategory">Limpar categoria</button>':''}</div>${shown.length?`<div class="public-card-grid">${shown.map(p=>{const m=mediaCache.get(p.id),cat=categories.find(c=>c.id===p.catalog_category_id);return `<article class="public-card"><div class="public-card-media">${m?.url?`<img src="${esc(m.url)}" alt="${esc(m.alt_text||p.nome)}" loading="lazy" referrerpolicy="no-referrer">`:''}</div><div class="public-card-copy">${cat?.nome?`<span class="public-eyebrow">${esc(cat.nome)}</span>`:''}<h3>${esc(p.nome)}</h3>${p.sku?`<p>SKU ${esc(p.sku)}</p>`:''}${Number(p.preco)>0?`<p class="public-price">${esc(money(p.preco))}</p>`:''}</div></article>`}).join('')}</div>`:'<div class="public-empty">Nenhum produto encontrado.</div>'}${pages>1?`<div style="display:flex;justify-content:center;gap:10px;align-items:center;margin-top:24px"><button class="public-close" type="button" id="prevProductPage" ${page<=1?'disabled':''}>Anterior</button><span>Página ${page} de ${pages}</span><button class="public-close" type="button" id="nextProductPage" ${page>=pages?'disabled':''}>Próxima</button></div>`:''}`;box.querySelector('#clearProductCategory')?.addEventListener('click',()=>{selectedCategory='';page=1;setUrl('','');renderProducts()});box.querySelector('#prevProductPage')?.addEventListener('click',()=>{if(page>1){page--;renderProducts();box.scrollIntoView({behavior:'smooth',block:'start'})}});box.querySelector('#nextProductPage')?.addEventListener('click',()=>{if(page<pages){page++;renderProducts();box.scrollIntoView({behavior:'smooth',block:'start'})}})}catch(e){console.error(e);box.innerHTML='<div class="public-empty">Não foi possível carregar os produtos agora.</div>'}}

try{const[f,c,p]=await Promise.all([supabase.from('catalog_families').select('*').eq('catalog_scope','produto').eq('ativo',true).order('ordem').order('nome'),supabase.from('catalog_categories').select('*').eq('catalog_scope','produto').eq('ativo',true).order('ordem').order('nome'),supabase.from('products').select('id,nome,sku,preco,catalog_category_id,ativo,product_type').eq('ativo',true).eq('product_type','produto').order('nome')]);if(f.error||c.error||p.error)throw f.error||c.error||p.error;families=f.data||[];categories=c.data||[];products=p.data||[];renderShell()}catch(e){console.error('Falha ao carregar catálogo de produtos.',e);root.innerHTML='<div class="public-shell"><div class="public-empty">Não foi possível carregar os produtos agora. Tente novamente em instantes.</div></div>'}
