// Run with NODE_PATH pointing to a Playwright installation. No database writes.
const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{let name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(name.endsWith('/'))name+='index.html';const file=path.join(root,name);if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);res.end();return}res.setHeader('Content-Type',types[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(4173,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage();const errors=[];page.on('console',m=>{if(m.type()==='error')console.log('console:',m.text())});page.on('response',r=>{if(r.status()>=400)console.log('HTTP',r.status(),r.url())});page.on('pageerror',e=>errors.push(e.message));const results=[];for(const width of [375,768,1440]){await page.setViewportSize({width,height:900});for(const route of ['/','/produtos/','/produtos/item/','/servicos/','/servicos/cartoes/','/digital/','/portfolio/','/sobre/','/contato/']){await page.goto('http://127.0.0.1:4173'+route);await page.waitForTimeout(800);assert.equal(await page.locator('.croma-standard-header').count(),1);if(!['/produtos/','/servicos/'].includes(route))assert.equal(await page.locator('h1').count(),1,route+' missing h1');const dims=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert(dims.scroll<=dims.width+1,route+' overflow at '+width);if(width<=768){const toggle=page.locator('.service-menu-toggle');await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await toggle.getAttribute('aria-expanded'),'false');}results.push({route,width,ok:true});}}
await page.goto('http://127.0.0.1:4173/contato/');await page.locator('[name=pedido]').fill('Cartões de visita');await page.locator('button[type=submit]').click();const link=await page.locator('#quoteSend').getAttribute('href');assert(new URL(link).searchParams.get('text').includes('\n'));await page.locator('[name=pedido]').fill('Adesivos');assert(await page.locator('#quoteSend').isHidden());
await page.goto('http://127.0.0.1:4173/produtos/');await page.waitForTimeout(5000);const products=await page.locator('a[href*="/produtos/item/?id="]').count();if(products){await page.locator('a[href*="/produtos/item/?id="]').first().click();await page.waitForTimeout(2000);assert(await page.locator('#productDetail h1').count());console.log('Live product detail:',await page.locator('#productDetail h1').innerText());}else console.log('Live catalog unavailable:',(await page.locator('main').innerText()).slice(0,240));
console.log(JSON.stringify({pages:results.length,products,errors},null,2));assert.deepEqual(errors,[]);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
