import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const API="https://api.bling.com.br/Api/v3", PAGE=100;
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const txt=(v:any)=>{const s=String(v??"").trim();return s||null};
const num=(v:any)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const pick=(o:any,paths:string[])=>{for(const p of paths){let x=o;for(const k of p.split("."))x=x?.[k];if(x!==undefined&&x!==null&&x!=="")return x}return null};
const err=(e:any)=>e instanceof Error?e.message:typeof e==="string"?e:JSON.stringify(e);
const service=(x:any)=>{const t=String(x?.tipo??"").toUpperCase();return t==="S"||t.includes("SERV")};
const origins=new Set(["https://www.cromapel.com.br","https://cromapel.com.br"]);
function cors(req:Request){const o=req.headers.get("Origin")||"";return{"Access-Control-Allow-Origin":origins.has(o)?o:"https://cromapel.com.br","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-croma-cron","Access-Control-Allow-Methods":"POST, OPTIONS",Vary:"Origin"}}
function json(req:Request,data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors(req),"Content-Type":"application/json"}})}
function stable(v:any):any{if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o:any={};for(const k of Object.keys(v).sort())o[k]=stable(v[k]);return o}return v}
async function hash(v:any){const b=new TextEncoder().encode(JSON.stringify(stable(v??null)));const d=await crypto.subtle.digest("SHA-256",b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function secret(name:string){const{data,error}=await db.rpc("erp_read_secret",{p_name:name});if(error)throw error;return String(data||"")}
async function store(name:string,value:string,description:string){const{error}=await db.rpc("erp_store_secret",{p_name:name,p_value:value,p_description:description});if(error)throw error}
function tokenName(k:string,id:string){return`erp_bling_${k}_token_${id.replaceAll("-","")}`}
async function auth(req:Request){const c=req.headers.get("x-croma-cron")||"";if(c){const expected=await secret("erp_bling_cron_secret");if(expected&&c===expected)return{cron:true,role:"cron"}}const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)throw new Error("Sessão ausente.");const{data,error}=await db.auth.getUser(token);if(error||!data.user)throw new Error("Sessão inválida.");const{data:p}=await db.from("profiles").select("role,ativo").eq("id",data.user.id).maybeSingle();if(!p?.ativo||!["owner","manager"].includes(p.role))throw new Error("Acesso restrito à gestão.");return{cron:false,role:p.role,userId:data.user.id}}
async function connection(){const{data,error}=await db.from("erp_connections").select("*").eq("provider","bling").single();if(error)throw error;return data}
async function refresh(c:any,t:any){const cid=await secret("erp_bling_client_id"),cs=await secret("erp_bling_client_secret"),rt=await secret(t.refresh_token_secret_name);const r=await fetch(`${API}/oauth/token`,{method:"POST",headers:{Authorization:`Basic ${btoa(`${cid}:${cs}`)}`,"Content-Type":"application/x-www-form-urlencoded","enable-jwt":"1"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:rt})});const p=await r.json();if(!r.ok)throw new Error(p?.error_description||p?.error?.description||"Falha ao renovar token.");const an=tokenName("access",c.id),rn=tokenName("refresh",c.id);await Promise.all([store(an,String(p.access_token||""),"Access token OAuth do Bling"),store(rn,String(p.refresh_token||""),"Refresh token OAuth do Bling")]);await db.from("erp_private_tokens").update({access_token_secret_name:an,refresh_token_secret_name:rn,expires_at:new Date(Date.now()+Number(p.expires_in||3600)*1000).toISOString(),updated_at:new Date().toISOString()}).eq("connection_id",c.id);await db.from("erp_connections").update({status:"connected",last_error:null,updated_at:new Date().toISOString()}).eq("id",c.id);return String(p.access_token||"")}
async function token(){const c=await connection();const{data:t,error}=await db.from("erp_private_tokens").select("*").eq("connection_id",c.id).single();if(error)throw error;if(c.status==="connected"&&new Date(t.expires_at).getTime()>Date.now()+90000){const a=await secret(t.access_token_secret_name);if(a)return{token:a,c}}return{token:await refresh(c,t),c}}
async function api(t:string,path:string,method="GET",body?:any){for(let a=0;a<4;a++){const r=await fetch(`${API}${path}`,{method,headers:{Authorization:`Bearer ${t}`,Accept:"application/json","Content-Type":"application/json","enable-jwt":"1"},body:body===undefined?undefined:JSON.stringify(body)});const raw=await r.text();let p:any={};try{p=raw?JSON.parse(raw):{}}catch{throw new Error(`Resposta inválida do Bling (${r.status}).`)}if(r.ok)return p;if(r.status===429&&a<3){await sleep(1200*(a+1));continue}throw new Error(p?.error?.description||p?.error?.message||p?.message||`Bling respondeu ${r.status}.`)}throw new Error("Limite do Bling excedido.")}
function unit(v:any){const x=String(v??"un").toLowerCase().trim(),m:any={un:"un",unid:"un",unidade:"un",m:"m",mt:"m",m2:"m2","m²":"m2",kg:"kg",cx:"cx",caixa:"cx",pct:"pct",kit:"kit"};return m[x]||"un"}
function slug(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)}
async function uniqueSlug(base:string,id?:string){const root=slug(base)||`produto-${Date.now()}`;for(let i=0;i<30;i++){const s=i?`${root}-${i+1}`:root;let q=db.from("products").select("id").eq("slug",s).limit(1);if(id)q=q.neq("id",id);const{data}=await q;if(!data?.length)return s}return`${root}-${Date.now()}`}
async function state(id:string){const{data}=await db.from("erp_product_sync_state").select("*").eq("product_id",id).maybeSingle();return data||null}
async function composition(id:string,remote:any){const{data:rows,error}=await db.from("product_components").select("component_product_id,quantity,position,external_component_id").eq("parent_product_id",id).eq("active",true).eq("sync_to_bling",true).order("position",{ascending:true});if(error)throw error;const{data:settings,error:se}=await db.from("product_composition_settings").select("stock_type,stock_posting").eq("product_id",id).maybeSingle();if(se)throw se;const ids=[...new Set((rows||[]).map((r:any)=>r.component_product_id).filter(Boolean))];const byId=new Map<string,any>();if(ids.length){const{data:parts,error:pe}=await db.from("products").select("id,nome,sku,bling_product_id").in("id",ids);if(pe)throw pe;for(const p of parts||[])byId.set(p.id,p)}const components=[];for(const row of rows||[]){const part=byId.get(row.component_product_id);const external=Number(part?.bling_product_id||row.external_component_id||0);if(!external)throw new Error(`Componente ${part?.nome||row.component_product_id} ainda não possui vínculo com o Bling.`);components.push({produto:{id:external},quantidade:Number(row.quantity)})}return{has:components.length>0,components,stockType:settings?.stock_type??remote?.estrutura?.tipoEstoque??null,stockPosting:settings?.stock_posting??remote?.estrutura?.lancamentoEstoque??null}}
async function saveState(id:string,remote:any,extra:any={}){const now=new Date().toISOString();const{error}=await db.from("erp_product_sync_state").upsert({product_id:id,sync_policy:"auto_bidirectional",baseline_payload:remote||null,baseline_hash:remote?await hash(remote):null,last_remote_check_at:now,updated_at:now,...extra},{onConflict:"product_id"});if(error)throw error}
async function findLocal(ext:any){let q=await db.from("products").select("*").eq("bling_product_id",String(ext.id)).maybeSingle();if(q.data)return q.data;const code=txt(ext.codigo);if(!code)return null;q=await db.from("products").select("*").or(`sku.eq.${code},bling_sku.eq.${code}`).limit(2);if((q.data?.length||0)>1)throw new Error(`Mais de um produto usa o SKU ${code}.`);return q.data?.[0]||null}
async function inbound(ext:any){if(service(ext))return{service:true};const now=new Date().toISOString(),code=txt(ext.codigo)||`BLING-${ext.id}`;let local=await findLocal(ext);const st=local?await state(local.id):null,remoteHash=await hash(ext);if(local&&st?.local_dirty){if(st.baseline_hash&&st.baseline_hash!==remoteHash){await saveState(local.id,st.baseline_payload||ext,{local_dirty:true,remote_change_detected:true,outbound_state:"conflict",last_error:"Alterado nos dois lados antes da sincronização."});return{conflict:true}}return{dirty:true}}
const payload:any={nome:txt(ext.nome)||`Produto Bling ${ext.id}`,sku:local?.sku||code,descricao:txt(pick(ext,["descricaoCurta","descricao"]))||local?.descricao||null,unidade:unit(ext.unidade),preco:Math.max(0,num(ext.preco)||0),ativo:!["I","INATIVO"].includes(String(ext.situacao??"A").toUpperCase()),catalog_category_id:local?.catalog_category_id??null,slug:local?.slug||await uniqueSlug(`${ext.nome||"produto"}-${code}`,local?.id),product_type:"produto",product_format:String(ext.formato||"").toLowerCase().includes("vari")?"variation":"simple",bling_product_id:num(ext.id),bling_parent_id:num(pick(ext,["produtoPai.id","idProdutoPai"])),bling_sku:code,bling_sync_status:"sincronizado",bling_last_synced_at:now,bling_sync_error:null,short_description:txt(ext.descricaoCurta),complementary_description:txt(ext.descricaoComplementar),external_link:txt(ext.linkExterno),video_link:txt(pick(ext,["video.url","video"])),notes:txt(pick(ext,["observacoes","observacao"])),metadata:{...(local?.metadata||{}),bling_raw:ext,bling_seen_at:now}};let saved:any;if(local){const q=await db.from("products").update(payload).eq("id",local.id).select("*").single();if(q.error)throw q.error;saved=q.data}else{const q=await db.from("products").insert(payload).select("*").single();if(q.error)throw q.error;saved=q.data}
const dim=ext.dimensoes||{},trib=ext.tributacao||{};const d={product_id:saved.id,brand:txt(pick(ext,["marca.nome","marca"])),model:txt(ext.modelo),gtin:txt(ext.gtin),gtin_tax:txt(pick(ext,["gtinEmbalagem","gtinTributavel"])),ncm:txt(pick(trib,["ncm"]))||txt(ext.ncm),origin:txt(pick(trib,["origem"]))||txt(ext.origem),gross_weight_kg:num(ext.pesoBruto),net_weight_kg:num(ext.pesoLiquido),width_cm:num(pick(dim,["largura"]))??num(ext.largura),height_cm:num(pick(dim,["altura"]))??num(ext.altura),depth_cm:num(pick(dim,["profundidade"]))??num(ext.profundidade),specifications:{bling_raw:ext}};const de=await db.from("product_details").upsert(d,{onConflict:"product_id"});if(de.error)throw de.error;await db.from("erp_entity_mappings").upsert({provider:"bling",entity_type:"product",local_id:saved.id,external_id:String(ext.id),sync_status:"synced",last_synced_at:now,updated_at:now,metadata:{codigo:code,nome:ext.nome||null}},{onConflict:"provider,entity_type,external_id"});await saveState(saved.id,ext,{last_inbound_at:now,local_dirty:false,dirty_fields:[],remote_change_detected:false,outbound_state:"clean",last_error:null});return{created:!local}}
function outbound(p:any,d:any,remote:any,structure:any,dirty:string[]=[]){const x=structuredClone(remote||{});delete x.id;delete x.dataCriacao;delete x.dataAlteracao;delete x.loja;x.nome=p.nome;x.codigo=p.bling_sku||p.sku||x.codigo;x.preco=Number(p.preco||0);x.unidade=p.unidade||x.unidade||"UN";x.situacao=p.ativo?"A":"I";x.tipo="P";if(p.short_description!==null)x.descricaoCurta=p.short_description;if(p.complementary_description!==null)x.descricaoComplementar=p.complementary_description;if(p.notes!==null)x.observacoes=p.notes;if(d?.gtin)x.gtin=d.gtin;if(d?.gtin_tax)x.gtinEmbalagem=d.gtin_tax;if(d?.net_weight_kg!=null)x.pesoLiquido=Number(d.net_weight_kg);if(d?.gross_weight_kg!=null)x.pesoBruto=Number(d.gross_weight_kg);if(d?.brand)x.marca=typeof x.marca==="object"?{...x.marca,nome:d.brand}:d.brand;if(structure?.has){x.formato="E";const e:any={...(x.estrutura||{}),componentes:structure.components};if(structure.stockType)e.tipoEstoque=structure.stockType;if(structure.stockPosting)e.lancamentoEstoque=structure.stockPosting;x.estrutura=e}else if(dirty.includes("estrutura")){x.formato="S";delete x.estrutura}return x}
async function push(t:string,p:any){if(!p||p.product_type!=="produto")return{skipped:true};const st=await state(p.id),{data:d}=await db.from("product_details").select("*").eq("product_id",p.id).maybeSingle();let remote:any=null;if(p.bling_product_id){remote=(await api(t,`/produtos/${p.bling_product_id}`))?.data||null;if(remote&&service(remote)){await saveState(p.id,remote,{local_dirty:false,dirty_fields:[],outbound_state:"manual_service",last_error:"Serviço permanece manual."});return{service:true}}if(st?.baseline_hash&&remote&&await hash(remote)!==st.baseline_hash){await saveState(p.id,st.baseline_payload||remote,{local_dirty:true,remote_change_detected:true,outbound_state:"conflict",last_error:"O Bling mudou antes do envio automático."});return{conflict:true}}}
const structure=await composition(p.id,remote||{});const proposed=outbound(p,d||{},remote||{},structure,st?.dirty_fields||[]);let external=p.bling_product_id;if(external)await api(t,`/produtos/${external}`,"PUT",proposed);else{const r=await api(t,"/produtos","POST",proposed);external=r?.data?.id||r?.id;if(!external)throw new Error("Bling não retornou o ID criado.");await db.from("products").update({bling_product_id:Number(external),bling_sku:p.sku}).eq("id",p.id)}await sleep(350);const fresh=(await api(t,`/produtos/${external}`))?.data;if(!fresh)throw new Error("Não foi possível reler o produto no Bling.");const now=new Date().toISOString();await db.from("products").update({bling_product_id:Number(external),bling_sku:txt(fresh.codigo)||p.bling_sku||p.sku,bling_sync_status:"sincronizado",bling_last_synced_at:now,bling_sync_error:null,metadata:{...(p.metadata||{}),bling_raw:fresh,bling_outbound_applied_at:now}}).eq("id",p.id);await db.from("erp_entity_mappings").upsert({provider:"bling",entity_type:"product",local_id:p.id,external_id:String(external),sync_status:"synced",last_synced_at:now,updated_at:now,metadata:{codigo:fresh.codigo||null,nome:fresh.nome||null}},{onConflict:"provider,entity_type,external_id"});await saveState(p.id,fresh,{last_outbound_at:now,last_inbound_at:now,local_dirty:false,dirty_fields:[],remote_change_detected:false,outbound_state:"clean",last_error:null});return{pushed:true,external}}
async function pushPending(t:string){const{data,error}=await db.from("erp_product_sync_state").select("product_id,updated_at").eq("local_dirty",true).in("outbound_state",["pending","review_required","error"]).order("updated_at",{ascending:true}).limit(12);if(error)throw error;let pushed=0,conflicts=0,errors=0,skipped=0;for(const s of data||[]){const{data:p}=await db.from("products").select("*").eq("id",s.product_id).maybeSingle();if(!p||p.product_type!=="produto"){skipped++;continue}await db.from("erp_product_sync_state").update({outbound_state:"syncing",updated_at:new Date().toISOString()}).eq("product_id",p.id);try{const r=await push(t,p);if(r.conflict)conflicts++;else if(r.pushed)pushed++;else skipped++}catch(e){errors++;const m=err(e);await db.from("products").update({bling_sync_status:"erro",bling_sync_error:m}).eq("id",p.id);await db.from("erp_product_sync_state").update({outbound_state:"error",last_error:m,updated_at:new Date().toISOString()}).eq("product_id",p.id)}await sleep(300)}return{pushed,conflicts,push_errors:errors,skipped}}
async function parents(){const{data}=await db.from("products").select("id,bling_parent_id,parent_product_id").eq("product_type","produto").not("bling_parent_id","is",null);for(const c of data||[]){const{data:p}=await db.from("products").select("id").eq("bling_product_id",c.bling_parent_id).maybeSingle();if(p?.id&&p.id!==c.parent_product_id)await db.from("products").update({parent_product_id:p.id}).eq("id",c.id)}}
async function pullPage(t:string,c:any,page:number,bootstrap:boolean){const started=new Date(),j=await db.from("erp_sync_jobs").insert({provider:"bling",entity_type:"product",operation:bootstrap?"reconcile":"incremental",direction:"bling_to_croma",status:"running",started_at:started.toISOString(),request_summary:{page,limit:PAGE,services:"manual"}}).select("id").single();let ok=0,created=0,services=0,conflicts=0,errors=0;const failed:any[]=[];try{const items=(await api(t,`/produtos?pagina=${page}&limite=${PAGE}`))?.data||[];for(const item of items){try{const full=(await api(t,`/produtos/${item.id}`))?.data;if(!full)throw new Error("Produto sem detalhe.");if(service(full)){services++;continue}const r=await inbound(full);if(r.conflict)conflicts++;else if(!r.dirty){ok++;if(r.created)created++}}catch(e){errors++;failed.push({id:item?.id,error:err(e)})}await sleep(300)}await parents();const more=items.length===PAGE,now=new Date().toISOString(),cfg={...(c.config||{}),products_auto_sync_enabled:true,products_auto_sync_services:false,products_auto_sync_interval_minutes:5};if(bootstrap){cfg.products_auto_bootstrap_active=more;cfg.products_auto_bootstrap_page=more?page+1:1;if(!more)cfg.products_auto_bootstrap_completed_at=now}else{cfg.products_auto_scan_page=more?page+1:1;cfg.products_auto_last_pull_at=now}await db.from("erp_connections").update({config:cfg,last_sync_at:now,last_error:errors?`${errors} produto(s) com erro`:null,updated_at:now}).eq("id",c.id);c.config=cfg;if(j.data?.id)await db.from("erp_sync_jobs").update({status:errors?"partial":"completed",processed_count:items.length,success_count:ok,error_count:errors,result_summary:{page,created,updated:ok-created,services_skipped:services,conflicts,errors,failed,has_more:more,next_page:more?page+1:1},finished_at:now}).eq("id",j.data.id);return{page,pulled:ok,created,services_skipped:services,conflicts,pull_errors:errors,has_more:more,next_page:more?page+1:1}}catch(e){if(j.data?.id)await db.from("erp_sync_jobs").update({status:"failed",error_count:1,error_message:err(e),finished_at:new Date().toISOString()}).eq("id",j.data.id);throw e}}
async function automatic(t:string,c:any){const pushed=await pushPending(t),cfg=c.config||{};if(cfg.products_auto_bootstrap_active)return{mode:"bootstrap",...pushed,...await pullPage(t,c,Number(cfg.products_auto_bootstrap_page||1),true)};const last=cfg.products_auto_last_pull_at?new Date(cfg.products_auto_last_pull_at).getTime():0;if(last&&Date.now()-last<270000)return{mode:"push_only",...pushed,skipped_pull:true};return{mode:"scan",...pushed,...await pullPage(t,c,Number(cfg.products_auto_scan_page||1),false)}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return json(req,{error:"Método não permitido."},405);try{const actor=await auth(req),input=await req.json().catch(()=>({})),action=String(input.action||"incremental_sync"),tk=await token();if(action==="full_sync"){if(!actor.cron&&actor.role!=="owner")return json(req,{error:"Apenas o proprietário pode iniciar sincronização completa."},403);const cfg={...(tk.c.config||{}),products_auto_sync_enabled:true,products_auto_sync_services:false,products_auto_bootstrap_active:true,products_auto_bootstrap_page:1,products_auto_bootstrap_started_at:new Date().toISOString(),products_auto_bootstrap_completed_at:null,products_auto_scan_page:1};await db.from("erp_connections").update({config:cfg,updated_at:new Date().toISOString()}).eq("id",tk.c.id);return json(req,{ok:true,...await automatic(tk.token,{...tk.c,config:cfg})})}if(action==="incremental_sync")return json(req,{ok:true,...await automatic(tk.token,tk.c)});if(action==="push_product"){const id=String(input.product_id||"");const{data:p}=await db.from("products").select("*").eq("id",id).single();if(!p)throw new Error("Produto não encontrado.");if(p.product_type!=="produto")return json(req,{ok:false,skipped:true,reason:"service_manual"});return json(req,{ok:true,...await push(tk.token,p)})}if(action==="status"){const{count}=await db.from("products").select("id",{count:"exact",head:true}).eq("product_type","produto").not("bling_product_id","is",null);return json(req,{ok:true,linked_products:count||0,config:tk.c.config||{}})}return json(req,{error:"Ação inválida."},400)}catch(e){console.error("bling_product_auto_sync_error",e);return json(req,{error:"Não foi possível sincronizar os produtos.",detail:err(e)},500)}});