import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const API="https://api.bling.com.br/Api/v3";
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const now=()=>new Date().toISOString();
const emsg=(e:any)=>e instanceof Error?e.message:String(e);
function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json"}})}
async function secret(n:string){const{data,error}=await db.rpc("erp_read_secret",{p_name:n});if(error)throw error;return String(data||"")}
async function store(n:string,v:string,d:string){const{error}=await db.rpc("erp_store_secret",{p_name:n,p_value:v,p_description:d});if(error)throw error}
function tokenName(k:string,id:string){return`erp_bling_${k}_token_${id.replaceAll("-","")}`}
async function authorize(req:Request){const cron=req.headers.get("x-croma-cron")||"";if(cron){const e=await secret("erp_bling_cron_secret");if(e&&cron===e)return}const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)throw new Error("Sessão ausente.");const{data,error}=await db.auth.getUser(token);if(error||!data.user)throw new Error("Sessão inválida.");const{data:p}=await db.from("profiles").select("role,ativo").eq("id",data.user.id).maybeSingle();if(!p?.ativo||p.role!=="owner")throw new Error("Apenas o proprietário pode sincronizar a taxonomia.")}
async function conn(){const{data,error}=await db.from("erp_connections").select("*").eq("provider","bling").single();if(error)throw error;return data}
async function refresh(c:any,t:any){const cid=await secret("erp_bling_client_id"),cs=await secret("erp_bling_client_secret"),rt=await secret(t.refresh_token_secret_name);const r=await fetch(`${API}/oauth/token`,{method:"POST",headers:{Authorization:`Basic ${btoa(`${cid}:${cs}`)}`,"Content-Type":"application/x-www-form-urlencoded","enable-jwt":"1"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:rt})}),p=await r.json();if(!r.ok)throw new Error(p?.error_description||p?.error?.description||"Falha ao renovar token do Bling.");const an=tokenName("access",c.id),rn=tokenName("refresh",c.id);await Promise.all([store(an,String(p.access_token||""),"Access token OAuth do Bling"),store(rn,String(p.refresh_token||""),"Refresh token OAuth do Bling")]);await db.from("erp_private_tokens").update({access_token_secret_name:an,refresh_token_secret_name:rn,expires_at:new Date(Date.now()+Number(p.expires_in||3600)*1000).toISOString(),updated_at:now()}).eq("connection_id",c.id);return String(p.access_token||"")}
async function access(){const c=await conn(),{data:t,error}=await db.from("erp_private_tokens").select("*").eq("connection_id",c.id).single();if(error)throw error;if(c.status==="connected"&&new Date(t.expires_at).getTime()>Date.now()+90000){const a=await secret(t.access_token_secret_name);if(a)return a}return refresh(c,t)}
async function api(t:string,path:string,method="GET",body?:any){for(let i=0;i<5;i++){const r=await fetch(`${API}${path}`,{method,headers:{Authorization:`Bearer ${t}`,Accept:"application/json","Content-Type":"application/json","enable-jwt":"1"},body:body===undefined?undefined:JSON.stringify(body)});const raw=await r.text();let p:any={};try{p=raw?JSON.parse(raw):{}}catch{p={message:raw}}if(r.ok)return p;if(r.status===429&&i<4){await sleep(1400*(i+1));continue}throw new Error(p?.error?.description||p?.error?.message||p?.message||`Bling respondeu ${r.status}.`)}throw new Error("Limite do Bling excedido.")}
function stable(v:any):any{if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o:any={};for(const k of Object.keys(v).sort())o[k]=stable(v[k]);return o}return v}
async function hash(v:any){const b=new TextEncoder().encode(JSON.stringify(stable(v??null))),d=await crypto.subtle.digest("SHA-256",b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function allProducts(){const out:any[]=[];for(let from=0;;from+=1000){const{data,error}=await db.from("products").select("id,bling_product_id,bling_parent_id,catalog_category_id,metadata").not("bling_product_id","is",null).not("catalog_category_id","is",null).order("id").range(from,from+999);if(error)throw error;const rows=data||[];out.push(...rows);if(rows.length<1000)break}return out}
async function categoryMap(){const{data,error}=await db.from("erp_entity_mappings").select("local_id,external_id").eq("provider","bling").eq("entity_type","category").not("local_id","is",null);if(error)throw error;return new Map((data||[]).map((m:any)=>[String(m.local_id),String(m.external_id)]))}
async function states(ids:string[]){const out=new Map<string,any>();for(let i=0;i<ids.length;i+=500){const{data,error}=await db.from("erp_product_sync_state").select("product_id,baseline_payload").in("product_id",ids.slice(i,i+500));if(error)throw error;for(const s of data||[])out.set(String(s.product_id),s.baseline_payload)}return out}
const terminal=(p:any)=>["synced","blocked"].includes(String(p?.metadata?.taxonomy_sync_status||""));
function putBody(base:any,cat:string){const x=structuredClone(base||{});for(const k of["id","dataCriacao","dataAlteracao","loja"])delete x[k];x.categoria={id:Number(cat)};return x}
async function markSynced(p:any,extCat:string,baseline:any,mode="direct",extra:any={}){const ts=now();await db.from("products").update({metadata:{...(p.metadata||{}),bling_raw:{...((p.metadata||{}).bling_raw||baseline||{}),categoria:{id:Number(extCat)}},taxonomy_sync_status:"synced",taxonomy_sync_mode:mode,taxonomy_external_category_id:extCat,taxonomy_synced_at:ts,taxonomy_sync_error:null,...extra},bling_sync_status:"sincronizado",bling_last_synced_at:ts,bling_sync_error:null}).eq("id",p.id);if(baseline){const next={...baseline,categoria:{id:Number(extCat)}};await db.from("erp_product_sync_state").update({baseline_payload:next,baseline_hash:await hash(next),last_outbound_at:ts,local_dirty:false,dirty_fields:[],remote_change_detected:false,outbound_state:"clean",last_error:null,updated_at:ts}).eq("product_id",p.id)}}
async function markBlocked(p:any,reason:string,mode:string,extra:any={}){const ts=now();await db.from("products").update({metadata:{...(p.metadata||{}),taxonomy_sync_status:"blocked",taxonomy_sync_mode:mode,taxonomy_sync_error:reason,taxonomy_sync_error_at:ts,...extra},bling_sync_status:"pendente",bling_sync_error:reason}).eq("id",p.id)}
async function markError(p:any,e:any){const m=emsg(e),ts=now();await db.from("products").update({metadata:{...(p.metadata||{}),taxonomy_sync_status:"error",taxonomy_sync_error:m,taxonomy_sync_error_at:ts},bling_sync_status:"erro",bling_sync_error:m}).eq("id",p.id)}

async function syncOne(t:string,p:any,base:any,extCat:string,all:any[]){
  const formato=String(base?.formato||"").toUpperCase();
  const variation=base?.variacao||null;
  const rawParent=variation?.produtoPai?.id??p.bling_parent_id??null;
  const parentExt=Number(rawParent)>0?String(rawParent):null;
  const cloneInfo=variation?.produtoPai?.cloneInfo;

  if(parentExt&&cloneInfo!==false){
    const parent=all.find(x=>String(x.bling_product_id)===parentExt);
    if(!parent){await markBlocked(p,"Variação vinculada a produto pai que ainda não está presente no catálogo local.","variation_parent_missing",{taxonomy_parent_bling_id:parentExt});return{blocked:true}}
    const ps=String(parent?.metadata?.taxonomy_sync_status||"");
    if(ps==="blocked"){await markBlocked(p,"Categoria da variação depende de um produto pai bloqueado para consolidação.","variation_inherited_blocked",{taxonomy_parent_bling_id:parentExt});return{blocked:true}}
    if(ps!=="synced")return{deferred:true};
    if(String(parent?.metadata?.taxonomy_external_category_id||"")!==String(extCat)){await markBlocked(p,"A variação configurada para clonar o pai possui classificação local diferente do produto pai.","variation_category_conflict",{taxonomy_parent_bling_id:parentExt});return{blocked:true}}
    await markSynced(p,extCat,null,"inherited_from_parent",{taxonomy_parent_bling_id:parentExt,taxonomy_clone_info:true});return{synced:true,inherited:true};
  }

  try{
    await api(t,`/produtos/${p.bling_product_id}`,"PUT",putBody(base,extCat));
    const mode=parentExt&&cloneInfo===false?"variation_independent":formato==="V"?"variation_parent":formato==="E"?"composition":"direct";
    await markSynced(p,extCat,{...base,categoria:{id:Number(extCat)}},mode,{taxonomy_parent_bling_id:parentExt,taxonomy_clone_info:cloneInfo??null});
    return{synced:true,variationParent:formato==="V",composition:formato==="E",independentVariation:!!(parentExt&&cloneInfo===false)};
  }catch(e){
    const m=emsg(e);
    if((formato==="V"||formato==="E")&&/valida/i.test(m)){await markBlocked(p,"Cadastro estruturado do Bling não aceita alteração de categoria pela API enquanto a grade/composição atual não passar na validação. Preservado para consolidação.",formato==="V"?"variation_parent_bling_validation":"composition_bling_validation",{taxonomy_expected_external_category_id:extCat,taxonomy_parent_bling_id:parentExt,taxonomy_clone_info:cloneInfo??null});return{blocked:true}}
    throw e;
  }
}

async function syncBatch(t:string,limit:number){const size=Math.max(1,Math.min(145,limit||90)),cmap=await categoryMap();const{count:expected}=await db.from("catalog_categories").select("id",{count:"exact",head:true}).eq("ativo",true);if(cmap.size!==(expected||0))return{skipped:true,reason:"categories_not_ready",mapped:cmap.size,expected:expected||0};const all=await allProducts(),pending=all.filter(p=>!terminal(p)).slice(0,size);if(!pending.length)return{processed:0,synced:0,blocked:0,errors:0,remaining:0,done:true};const smap=await states(pending.map(p=>p.id));let synced=0,blocked=0,errors=0,deferred=0,inherited=0,variationParents=0,compositions=0,independentVariations=0;for(const p of pending){try{const extCat=cmap.get(String(p.catalog_category_id)),base=smap.get(String(p.id));if(!extCat)throw new Error("Categoria sem mapeamento Bling.");if(!base)throw new Error("Produto sem payload-base do Bling.");const r=await syncOne(t,p,base,extCat,all);if(r.deferred)deferred++;else if(r.blocked)blocked++;else if(r.synced){synced++;if(r.inherited)inherited++;if(r.variationParent)variationParents++;if(r.composition)compositions++;if(r.independentVariation)independentVariations++}}catch(e){errors++;await markError(p,e)}await sleep(380)}const fresh=await allProducts(),remaining=fresh.filter(p=>!terminal(p)).length;return{processed:pending.length,synced,blocked,errors,deferred,inherited,variationParents,compositions,independentVariations,remaining,done:remaining<=0}}
async function status(){const[cmap,rows]=await Promise.all([categoryMap(),allProducts()]);const{count:local}=await db.from("catalog_categories").select("id",{count:"exact",head:true}).eq("ativo",true);const synced=rows.filter((p:any)=>p?.metadata?.taxonomy_sync_status==="synced").length,blocked=rows.filter((p:any)=>p?.metadata?.taxonomy_sync_status==="blocked").length,errors=rows.filter((p:any)=>p?.metadata?.taxonomy_sync_status==="error").length,pending=rows.filter(p=>!terminal(p)).length;return{local_categories:local||0,mapped_categories:cmap.size,products:rows.length,synced_products:synced,blocked_products:blocked,pending_products:pending,error_products:errors}}
async function pushMissing(t:string){const{data:cats,error}=await db.from("catalog_categories").select("id,nome,parent_id,catalog_scope,updated_at").eq("ativo",true).order("ordem").order("nome");if(error)throw error;const cmap=await categoryMap();let created=0;const ordered=[...(cats||[]).filter((c:any)=>!c.parent_id),...(cats||[]).filter((c:any)=>c.parent_id)];for(const c of ordered){if(cmap.has(String(c.id)))continue;let pe:string|null=null;if(c.parent_id){pe=cmap.get(String(c.parent_id))||null;if(!pe)throw new Error(`Categoria pai sem mapeamento: ${c.nome}`)}const p=await api(t,"/categorias/produtos","POST",{descricao:c.nome,categoriaPai:pe?{id:Number(pe)}:null}),eid=String(p?.data?.id??p?.id??"");if(!eid)throw new Error(`Bling não retornou ID para ${c.nome}`);const ts=now();cmap.set(String(c.id),eid);await db.from("erp_entity_mappings").upsert({provider:"bling",entity_type:"category",local_id:c.id,external_id:eid,sync_status:"synced",local_updated_at:c.updated_at,last_synced_at:ts,updated_at:ts,metadata:{external_name:c.nome,parent_external_id:pe,catalog_scope:c.catalog_scope,taxonomy_rebuild_at:ts}},{onConflict:"provider,entity_type,external_id"});created++;await sleep(380)}return{created,mapped:cmap.size,total:cats?.length||0}}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"Método não permitido."},405);try{await authorize(req);const input=await req.json().catch(()=>({})),action=String(input.action||"status");if(action==="status")return json({ok:true,...await status()});const t=await access();if(action==="push_missing_categories")return json({ok:true,...await pushMissing(t)});if(action==="sync_products_batch")return json({ok:true,...await syncBatch(t,Number(input.limit||90))});return json({error:"Ação inválida."},400)}catch(e){console.error("bling_taxonomy_sync_error",e);return json({ok:false,error:emsg(e)},500)}});
