import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}});

function cors(req:Request){const origin=req.headers.get('Origin')||'';const allowed=['https://www.cromapel.com.br','https://cromapel.com.br'];return {'Access-Control-Allow-Origin':allowed.includes(origin)?origin:'https://www.cromapel.com.br','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json','Vary':'Origin'}}
function json(req:Request,data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:cors(req)})}
async function requireManager(req:Request){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)throw new Response('Sessão ausente.',{status:401});const{data,error}=await admin.auth.getUser(token);if(error||!data.user)throw new Response('Sessão inválida.',{status:401});const{data:profile,error:pe}=await admin.from('profiles').select('id,role,ativo').eq('id',data.user.id).maybeSingle();if(pe||!profile?.ativo||!['owner','manager'].includes(profile.role))throw new Response('Acesso restrito à gestão.',{status:403});return data.user}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});try{if(req.method!=='POST')return json(req,{error:'Método não permitido.'},405);await requireManager(req);const input=await req.json();if(input.action!=='link_product')return json(req,{error:'Ação inválida.'},400);const catalogId=String(input.catalog_item_id||'');const productId=String(input.product_id||'');if(!catalogId||!productId)return json(req,{error:'Item e produto são obrigatórios.'},400);
const{data:item,error:ie}=await admin.from('integration_catalog_items').select('*').eq('id',catalogId).maybeSingle();if(ie||!item)return json(req,{error:'Item de integração não encontrado.'},404);if(item.provider!=='bling'||item.entity_type!=='product')return json(req,{error:'Item incompatível.'},400);const{data:product,error:pe}=await admin.from('products').select('id,nome').eq('id',productId).maybeSingle();if(pe||!product)return json(req,{error:'Produto Croma não encontrado.'},404);
const now=new Date().toISOString();const{error:u1}=await admin.from('products').update({bling_product_id:Number(item.external_id),bling_sku:item.sku||null,bling_sync_status:'linked',updated_at:now}).eq('id',productId);if(u1)throw u1;const{error:u2}=await admin.from('integration_catalog_items').update({linked_product_id:productId,updated_at:now}).eq('id',catalogId);if(u2)throw u2;const{error:u3}=await admin.from('erp_entity_mappings').upsert({provider:'bling',entity_type:'product',local_id:productId,external_id:item.external_id,sync_status:'linked',last_synced_at:now,updated_at:now},{onConflict:'provider,entity_type,external_id'});if(u3)throw u3;return json(req,{ok:true,product_id:productId,product_name:product.nome});
}catch(error){if(error instanceof Response)return json(req,{error:await error.text()},error.status);console.error(error);return json(req,{error:'Não foi possível concluir o vínculo.',detail:error instanceof Error?error.message:String(error)},500)}});
